/*
 * Infomaniak Calendar - Multiplatform
 * Copyright (C) 2026 Infomaniak Network SA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.infomaniak.multiplatform_calendar.core.domain.model.event.recurrence

import com.infomaniak.multiplatform_calendar.core.domain.model.event.Event

/**
 * Where an [Event] stands in a recurring series, so an app can tell what a user action applies to.
 * Without it an override, which carries no rule of its own, passes for a plain event.
 *
 * Reporting [Master] or [Occurrence] depends on how the event was read: by id for the former, by
 * date range for the latter.
 */
public enum class EventRecurrenceState {
    /** Not part of any series. A user action applies to the event itself, with nothing to ask. */
    None,

    /** The series itself, carrying the rule every occurrence is generated from. */
    Master,

    /** One occurrence of a series, generated by its rule, listed as an `RDATE`, or overridden. */
    Occurrence,
}
